// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmb4dGZXKugtaGedVA8N2D5NScJZAMFL0',
    appId: '1:924093649099:web:d2ebbef48670a610ef8b4e',
    messagingSenderId: '924093649099',
    projectId: 'major-project-f975c',
    authDomain: 'major-project-f975c.firebaseapp.com',
    storageBucket: 'major-project-f975c.firebasestorage.app',
    measurementId: 'G-D2NW8L3G3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa5u8nDY0lvnbbQGXwuUArFvfHpxNKhJI',
    appId: '1:924093649099:android:63460ec3bb6c98c2ef8b4e',
    messagingSenderId: '924093649099',
    projectId: 'major-project-f975c',
    storageBucket: 'major-project-f975c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWPJc86NKbRmwpe_Xkbhl-LQ3tt5GXXI',
    appId: '1:924093649099:ios:9ddaebbf46a6d3b8ef8b4e',
    messagingSenderId: '924093649099',
    projectId: 'major-project-f975c',
    storageBucket: 'major-project-f975c.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWPJc86NKbRmwpe_Xkbhl-LQ3tt5GXXI',
    appId: '1:924093649099:ios:9ddaebbf46a6d3b8ef8b4e',
    messagingSenderId: '924093649099',
    projectId: 'major-project-f975c',
    storageBucket: 'major-project-f975c.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmb4dGZXKugtaGedVA8N2D5NScJZAMFL0',
    appId: '1:924093649099:web:5c9778e94fff2541ef8b4e',
    messagingSenderId: '924093649099',
    projectId: 'major-project-f975c',
    authDomain: 'major-project-f975c.firebaseapp.com',
    storageBucket: 'major-project-f975c.firebasestorage.app',
    measurementId: 'G-3ZB3PXFRQD',
  );
}
